### ISSUE TITLE
document.creation et document.creation_not_after ne sont pas réindexées quand le format de date n'est pas valide

### ISSUE THREAD

**Issue by MrGecko** [chartes/lettres-app#1]
#2

Problème lors de l'enregistrement de dates du style  **1578-10-JJ** ou **1560-MM-JJ** 

Problème au niveau du type de champ indexé par ES : 
```elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'failed to parse field [creation] of type [date]')```

TODO : à changer dans la facade du Document.

**Comment by morganlegal** [comment]
Le fix du #2 doit corriger celui-ci ou du moins l'empêcher
