### ISSUE TITLE
Les champs DateField ne sont pas sauvegardés à la perte du focus

### ISSUE THREAD

**Issue by MrGecko** [chartes/lettres-app#18]
Il semblerait que les champs DateFields ne déclenchent des submits uniquement lorsqu'on appuie sur Enter pour valider le champ. Si on clique en dehors, le submit n'est pas envoyé.

Cela n'arrive pas avec les autres champs (ex: creation-label)

**Comment by morganlegal** [comment]
Je n'ai pas le problème
