### ISSUE TITLE
Le chargement de la page d'édition de document ne se termine pas 

### ISSUE THREAD

**Issue by MrGecko** [chartes/lettres-app#24]
Chargement sans fin de la page d'édition lorsqu'on est connecté (testé sous chrome (ça le fait planter) et firefox en dev et en prod, indexes mis à jour).

**Comment by MrGecko** [comment]
serait apparu avec 99f42a513821cd74a1c3a0827524a79086330551

**Comment by morganlegal** [comment]
Je pense que c'est apparu avant parce que j'ai eu un épisode comme ça quand j'ai fait un pull lundi pour récupérer tes changements

**Comment by MrGecko** [comment]
Je retenterai aujourd'hui. Le problème n'apparaissait pas lorsque j'ai uniquement checkout le commit avant celui-ci.

**Comment by MrGecko** [comment]
Le problème se produit lorsqu'il y a un caractère de retour à la ligne entre deux <p></p> dans le RichTextEditor

**Comment by morganlegal** [comment]
Tu as un exemple de document ?

**Comment by MrGecko** [comment]
La majorité des documents, à commencer par le n°1.

**Comment by morganlegal** [comment]
Tu as le problème avec les données qui sont dans la base ou bien une fois qu'elles ont été éditées ?

**Comment by MrGecko** [comment]
Les deux. C'est en les éditant à la main en base que j'ai pu identifeir le problème existant dans les données.

**Comment by morganlegal** [comment]
Les données ont changé. Parce que je n'avais pas le problème avant ce matin
