### ISSUE TITLE
les liens vers les personnes/lieux n'ont pas de cible (juste un id)

### ISSUE THREAD

**Issue by MrGecko** [chartes/lettres-app#30]
Les liens vers les personnes/lieux n'ont pas de cible (juste un id) et ne sont donc pas cliquables.
Solution: ajouter l'attribut href prenant pour valeur le champ ref de la personne/lieu en question.

**Comment by MrGecko** [comment]
et ajouter un target="_blank" :)

**Comment by architexte** [comment]
Pas de lien sans cible. Créer les routes et pages adhoc.
