### ISSUE TITLE
Filtrer les requêtes sur l’API Wikidata

### ISSUE THREAD

**Issue by architexte** [chartes/lettres-app#40]
Pouvoir paramétrer le composant de requête sur l’API Wikidata par type d’entité, selon le champ du formulaire :
- [Human](https://www.wikidata.org/wiki/Q5) pour les Correspondants
- [City](https://www.wikidata.org/wiki/Q515) pour les Lieux
- Institutions (???) pour les institutions de conservation (difficile: musée, bibliothèque, etc.)

**Comment by MrGecko** [comment]
Il sera probablement nécessaire d'attaquer les services en SPARQL car la lib utilisée, aux dernières nouvelles, ne permet pas de faire ces distinctions (et ils l'assument).
