### ISSUE TITLE
Corriger le problème de définition de certaines foreign keys

### ISSUE THREAD

**Issue by MrGecko** [chartes/lettres-app#80]
Il y a un conflit sur certaines FK entre l'orm et la structure de la base : 

```python
SAWarning: relationship 'PersonHasRole.changes' will copy column person_has_role.id to column changelog.object_id, which conflicts with relationship(s): 'Document.changes' (copies document.id to changelog.object_id), 'Collection.changes' (copies collection.id to changelog.object_id), 'Note.changes' (copies note.id to changelog.object_id), 'Witness.changes' (copies witness.id to changelog.object_id), 'Institution.changes' (copies institution.id to changelog.object_id), 'Image.changes' (copies image.id to changelog.object_id), 'Language.changes' (copies language.id to changelog.object_id), 'Placename.changes' (copies placename.id to changelog.object_id), 'PlacenameRole.changes' (copies placename_role.id to changelog.object_id), 'PlacenameHasRole.changes' (copies placename_has_role.id to changelog.object_id), 'Person.changes' (copies person.id to changelog.object_id), 'PersonRole.changes' (copies person_role.id to changelog.object_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.
  util.warn(
```

**Comment by ethieblin** [comment]
Pouvez-vous détailler après quelle manipulation vous obtenez ce message d'erreur ?

**Comment by vicpsl** [comment]
Bonjour Elodie,
le message d'erreur est obtenu dans le terminal immédiatement après le lancement de l'application (python3 flask_app.py) : 

**Terminal au lancement de l'application :**

(lettresenv) USER:~/PROJET_PATH/lettres-app$ python3 flask_app.py
Load environment variables for config 'dev'
THIS APP IS IN DEV MODE. YOU SHOULD NOT SEE THIS IN PRODUCTION.
sqlite://///home/jboby/Projets/Lettres/lettres-app/db/lettres.dev.sqlite
/home/jboby/Projets/Lettres/lettresenv/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py:3435: SAWarning: relationship 'Collection.changes' will copy column collection.id to column changelog.object_id, which conflicts with relationship(s): 'Document.changes' (copies document.id to changelog.object_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning. (...)

Merci

**Comment by vicpsl** [comment]
Closed by PR add overlaps to changes relationship #98 .
