### ISSUE TITLE
Lenteur de mise à jour des attributs sur les collections de taille importante

### ISSUE THREAD

**Issue by vicpsl** [chartes/lettres-app#88]
La mise à jour des attributs (titre, description, curator) d'une collection de taille importante (ex : Catherine de Médicis, /collections/1) peut prendre relativement longtemps.

_Originally posted by @carinedengler in https://github.com/chartes/lettres-app/issues/87#issuecomment-1359581257_

**Comment by MrGecko** [comment]
Peut-être qu'au retour du PATCH vous ne souhaitez pas récupérer l'objet en entier (avec toutes ses relations !)
Deux pistes :
- Essayer de faire un PATCH sur une facade sans relations
- Essayer d'ajouter de quoi paramétrer le patch en ajoutant un without-relationships (actuellement c'est en dur)
https://github.com/chartes/lettres-app/blob/17337425ead197d98c730c3d7e284edcc0f09cc6/app/api/route_registrar.py#L1300-L1301

**Comment by fbessou** [comment]
Après analyse plus précise, il semblerait que l'essentiel du temps soit passé à collecter les documents à ré-indexer  ET à réindexer ceux-ci. Je pense qu'on peut gagner beaucoup de temps sur l'indexation en passant par l'API bulk.

Dans le cas de la collection "Catherine de Médicis", une mise à jour du titre dure 41.5s chez moi dont :

- 2.5s de construction de la réponse
- 17s de collecte des documents à ré-indexer
- 22s d'indexation

**Comment by fbessou** [comment]
Je confirme que passer par une requête bulk réduit à ~0s le temps d'indexation on passe donc à ~20s au total.
Le plus gros du temps restant est pris par la construction des payloads à envoyer à ES et en particulier ceux des documents liés à la collection. Aujourd'hui on envoi les documents à indexer en entier, donc il faut charger tous leurs attributs et toutes leurs relations depuis la base de données. 

Il faudrait qu'on soit capable de ne modifier que le champ "collections" d'un document lorsqu'une de ses collections est modifiée. À voir comment cette solution pourrait s'intégrer dans l'architecture actuelle.

Une autre possibilité serait de modifier les mappings, mais il faudrait qu'on garde le lien entre documents et collections. Peut être que @ethieblin pourra donner son point de vue sur la question.
